name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['8.10.7']
        cabal: ['3.6.2.0']

    steps:
    - uses: actions/checkout@v2

    - name: Setup Haskell
      uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-${{ hashFiles('**/*.cabal') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-cabal-

    - name: Install Dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests

    - name: Build
      run: cabal build all

    - name: Run Tests
      run: cabal test all --test-show-details=always

    - name: Check Code Formatting
      run: |
        curl -sSL https://raw.githubusercontent.com/haskell/stylish-haskell/master/scripts/latest.sh | sh -s -- -f
        find . -name "*.hs" -not -path "./dist-*/*" -exec stylish-haskell -i {} +
        git diff --exit-code

    - name: Generate Documentation
      run: cabal haddock

  plutus-check:
    name: Plutus Validation
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Setup Plutus
      run: |
        git clone https://github.com/input-output-hk/plutus-apps
        cd plutus-apps
        git checkout v1.2.0
        nix-build -A plutus-apps.haskell.packages.plutus-core

    - name: Validate Plutus Scripts
      run: |
        cabal run fan-tan-deploy -- validate-scripts
